server_name: "File Server - Media"
server_base_url: "http://localhost:5954"
server_live_url: "http://localhost:5954"
server_private_url: "http://192.168.4.23:5954"
# server_public_url: "https://media.example.com"
server_public_url: "http://192.168.4.23:5954"
server_port: "5954"
server_api_key: "asdf"
browser_api_key: "asdf"
server_login_url_prefix: "asdf"
server_cookie_name: "file-server-media"
server_cookie_secret: "asdf="
server_cookie_secret_message: "why"
admin_username: "asdf"
admin_password: "asdf"
time_zone: "America/New_York"
save_files_path: "/home/morphs/SAVE_FILES"
encryption_key: "asdf"
bolt_db_path: "bolt.db"
redis_address: "localhost:6379"
# redis_address: "private-redis:6379"
redis_db_number: 6
redis_password: ""
files_url_prefix: "asdf"
allow_origins: "https://asdf.asdf.com, https://asdf.asdf.com"
session_key: "asdf"
library_global_redis_key: "fileserver-media"
library:
  tv_shows:
    file_path: "/Users/morpheous/WORKSPACE/GO/FileServer-Media/TVShows.yaml"
    redis_key: "TVShows"
  movies:
    file_path: "/Users/morpheous/WORKSPACE/GO/FileServer-Media/moives.yaml"
    redis_key: "Movies"